# Generated by Django 3.2.13 on 2023-03-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LatestUpdate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastestupdates',
            name='image',
        ),
    ]
