# Generated by Django 3.2.13 on 2023-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LatestUpdate', '0003_lastestupdates_image_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestupdates',
            name='latest_update_table_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lastestupdates',
            name='latest_update_table_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
