# Generated by Django 3.2.13 on 2023-08-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_memeber_has_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel8CustomMemberServiceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('paystack_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rel8CustomServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField()),
                ('intro_text', models.TextField()),
                ('fields_subbission', models.JSONField(default=dict)),
                ('file_subbission', models.JSONField(default=dict)),
                ('is_paid', models.BooleanField(default=False)),
                ('break_down_of_payment', models.JSONField(default=dict)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Rel8CustomMemberServiceRequestTextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.FileField(upload_to='servicerequestfile/%d/')),
                ('customMember_service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customservices.rel8custommemberservicerequests')),
            ],
        ),
        migrations.CreateModel(
            name='Rel8CustomMemberServiceRequestsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('customMember_service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customservices.rel8custommemberservicerequests')),
            ],
        ),
        migrations.AddField(
            model_name='rel8custommemberservicerequests',
            name='custom_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customservices.rel8customservices'),
        ),
        migrations.AddField(
            model_name='rel8custommemberservicerequests',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.memeber'),
        ),
    ]
