# Generated by Django 3.2.13 on 2023-09-01 14:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rel8custommemberservicerequesttextfile',
            name='value',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='servicerequestfile/%d/'),
        ),
    ]
