# Generated by Django 3.2.13 on 2023-02-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='userSecret',
            field=models.TextField(default=''),
        ),
    ]
