# Generated by Django 3.2.13 on 2022-09-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeber',
            name='d',
            field=models.CharField(default='', max_length=2),
        ),
    ]
