# Generated by Django 3.2.13 on 2022-09-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_memeber_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeber',
            name='d',
        ),
    ]
