# Generated by Django 3.2.13 on 2023-02-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230205_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('chapter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters')),
                ('member', models.ManyToManyField(to='account.Memeber')),
            ],
        ),
    ]
