# Generated by Django 3.2.13 on 2023-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeber',
            name='bio',
            field=models.TextField(default='Bio Update'),
        ),
    ]
