# Generated by Django 3.2.13 on 2023-02-07 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230208_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberemploymenthistory',
            name='member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.memeber'),
        ),
    ]
