# Generated by Django 3.2.13 on 2022-09-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemberinfo',
            name='value',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
