# Generated by Django 3.2.13 on 2023-02-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_memberemploymenthistory_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipgrade',
            name='member',
            field=models.ManyToManyField(blank=True, default=None, to='account.Memeber'),
        ),
    ]
