# Generated by Django 4.2.15 on 2024-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_memeber_has_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="memeber",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="memeber",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="memeber",
            name="yog",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="chapters",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
