# Generated by Django 3.2.13 on 2022-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usermemberinfo_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='user_image/%d/'),
        ),
    ]
