# Generated by Django 3.2.13 on 2022-12-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excorole',
            name='chapter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters'),
        ),
    ]
