# Generated by Django 3.2.13 on 2022-12-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_excorole_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excorole',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber'),
        ),
    ]
