# Generated by Django 4.2.15 on 2024-08-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_memeber_origin_state_memeber_physical_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memeber",
            name="origin_state",
        ),
        migrations.RemoveField(
            model_name="memeber",
            name="physical_address",
        ),
        migrations.RemoveField(
            model_name="memeber",
            name="residential_country",
        ),
        migrations.RemoveField(
            model_name="memeber",
            name="residential_state",
        ),
        migrations.RemoveField(
            model_name="memeber",
            name="title",
        ),
    ]
