# Generated by Django 3.2.13 on 2022-12-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_excorole_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excorole',
            name='member',
        ),
        migrations.AddField(
            model_name='excorole',
            name='member',
            field=models.ManyToManyField(null=True, to='account.Memeber'),
        ),
    ]
