# Generated by Django 3.2.13 on 2022-12-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20221214_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excorole',
            name='member',
            field=models.ManyToManyField(to='account.Memeber'),
        ),
    ]
