# Generated by Django 3.2.13 on 2023-01-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Election 1', max_length=300)),
                ('role_name', models.CharField(default='Role OF What?', max_length=300)),
                ('role_detail', models.TextField(default='')),
                ('is_close', models.BooleanField(default=False)),
                ('members_that_has_cast_thier_vote', models.ManyToManyField(to='account.Memeber')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vote', models.IntegerField()),
                ('youtubeVidLink', models.TextField()),
                ('ballotbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ballotbox')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.memeber')),
            ],
        ),
    ]
