# Generated by Django 3.2.13 on 2023-02-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='ballotbox',
        ),
    ]
