# Generated by Django 3.2.13 on 2023-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotbox',
            name='election_endDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ballotbox',
            name='election_endTime',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ballotbox',
            name='election_startDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ballotbox',
            name='election_startTIme',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='aspirantBio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contestant',
            name='upload_manifesto_docs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contestant',
            name='upload_manifesto_image',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
