# Generated by Django 3.2.13 on 2023-02-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20230202_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='upload_manifesto_docs',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
