# Generated by Django 3.2.13 on 2023-02-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_contestant_upload_manifesto_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='aspirantBio',
            field=models.JSONField(default=None, null=True),
        ),
    ]
