# Generated by Django 3.2.13 on 2023-02-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20230211_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='postions',
            name='ballotbox',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.ballotbox'),
        ),
    ]
