# Generated by Django 3.2.13 on 2023-02-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_postions_ballotbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotbox',
            name='members_that_has_cast_thier_vote',
        ),
    ]
