FROM python:3.11.5-

WORKDIR /app


ADD requirements.txt .

RUN pip install -r requirements.txt

ADD . .

EXPOSE 8000

CMD python manage.py migrate_schemas --shared
CMD python manage.py migrate
CMD python manage.py init_public_client
CMD python manage.py init_admin

CMD daphne rel8.asgi:application --port $PORT --bind 0.0.0.0 -v2