# Generated by Django 3.2.13 on 2022-08-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_exco', models.BooleanField(default=False)),
                ('is_committe', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(null=True)),
                ('dislikes', models.IntegerField(null=True)),
                ('body', models.TextField(default=' ')),
                ('image', models.ImageField(default=None, null=True, upload_to='newsImage/%d/')),
                ('chapters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters')),
                ('commitee_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commiteegroup')),
                ('user_that_have_reacted', models.ManyToManyField(blank=True, to='account.Memeber')),
            ],
        ),
    ]
