# Generated by Django 4.2.15 on 2024-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="news",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
