# Generated by Django 5.1.4 on 2025-01-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_dislikes_alter_news_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_for_members_only',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
