# Generated by Django 3.2.13 on 2022-09-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usermemberinfo_value'),
        ('news', '0003_news_danload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='chapters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters'),
        ),
        migrations.AlterField(
            model_name='news',
            name='commitee_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commiteegroup'),
        ),
        migrations.AlterField(
            model_name='newsparagraph',
            name='heading',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='newsparagraph',
            name='paragragh',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
