# Generated by Django 3.2.13 on 2022-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220913_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='danload',
            field=models.FileField(default=None, null=True, upload_to='newsFileDanload/%d/'),
        ),
    ]
