# Generated by Django 3.2.13 on 2023-02-20 20:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberofreissuanceofcertificate',
            name='attach_membership_receipt',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='attach_membership_receipt/%m/%d/'),
        ),
    ]
