# Generated by Django 3.2.13 on 2023-02-20 20:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequest', '0002_alter_memberofreissuanceofcertificate_attach_membership_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeofname',
            name='attach_membership_certificate',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='attach_membership_certificate/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='changeofname',
            name='membership_due_receipt',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='membership_due_receipt/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='changeofname',
            name='upload_financial_statement',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload_financial_statement/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='changeofname',
            name='upload_incorporation_certificate',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload_incorporation_certificate/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='deactivationofmembership',
            name='deactivation_request',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='deactivation_request/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='deactivationofmembership',
            name='submit_most_recent_financial_statement',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='submit_most_recent_financial_statement/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='deactivationofmembership',
            name='upload_all_levy_recipt',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload_all_levy_recipt/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='factorylocationupdate',
            name='proceed_to_update_your_profile',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='proceed_to_update_your_profile/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='factorylocationupdate',
            name='submit_most_recent_financial_statement',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='submit_most_recent_financial_statement/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='factorylocationupdate',
            name='upload_dues_reciept',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='Upload_dues_reciept/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='factorylocationupdate',
            name='upload_factory_inspection_report',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload_factory_inspection_report/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mergerofcompanies',
            name='submit_most_recent_financial_statement',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='submit_most_recent_financial_statement/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mergerofcompanies',
            name='upload_dues_reciept',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='Upload_dues_reciept/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mergerofcompanies',
            name='upload_membership_cert_for_both_companies',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='Upload_membership_cert_for_both_companies/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mergerofcompanies',
            name='upload_request_letter',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload_request_letter/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productmanufacturingupdate',
            name='proceed_to_update_your_profile',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='proceed_to_update_your_profile/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productmanufacturingupdate',
            name='submit_most_recent_financial_statement',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='submit_most_recent_financial_statement/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productmanufacturingupdate',
            name='upload_Product_update_report',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload_Product_update_report/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productmanufacturingupdate',
            name='upload_all_levy_recipt',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload_all_levy_recipt/%m/%d/'),
        ),
    ]
