# Generated by Django 3.2.13 on 2022-12-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_photo'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='chapters',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters'),
        ),
    ]
