# Generated by Django 3.2.13 on 2023-03-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundaproject',
            name='what_project_needs',
            field=models.JSONField(default=None, null=True),
        ),
    ]
