# Generated by Django 3.2.13 on 2023-01-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_excorole_member'),
        ('extras', '0002_gallery_chapters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_taken', models.DateTimeField()),
                ('chapters', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesForGalleryV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_v2/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.galleryv2')),
            ],
        ),
    ]
