# Generated by Django 3.2.13 on 2023-02-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_auto_20230208_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundaproject',
            name='amount_made',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
