# Generated by Django 3.2.13 on 2023-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_alter_supportprojectincash_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportprojectincash',
            name='member_remark',
            field=models.TextField(default='Will donate'),
        ),
    ]
