# Generated by Django 3.2.13 on 2023-02-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_memberemploymenthistory_member'),
        ('extras', '0005_fundaproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReissuanceOfCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_info', models.TextField(default='')),
                ('file', models.FileField(upload_to='certificates_reissue/%d/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.memeber')),
            ],
        ),
    ]
