# Generated by Django 3.2.13 on 2023-06-26 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_supportprojectincash_member_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportprojectinkind',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
