# Generated by Django 3.2.13 on 2023-06-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_memeber_bio'),
        ('extras', '0006_supportprojectinkind_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPersonalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to='gallery_personal/')),
                ('member', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.memeber')),
            ],
        ),
    ]
