# Generated by Django 3.2.13 on 2023-02-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_alter_reissuanceofcertificate_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReissuanceOfCertificate',
        ),
    ]
