# Generated by Django 4.2.15 on 2024-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0007_memberpersonalgallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportprojectincash",
            name="paystack_key",
            field=models.TextField(default="", unique=True),
        ),
    ]
