# Generated by Django 3.2.13 on 2023-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0009_customersupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fixing', 'Fixing'), ('attended_to', 'Attended To')], default='pending', max_length=50),
        ),
    ]
