# Generated by Django 3.2.13 on 2023-03-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationofdeactivatedmember',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber'),
        ),
        migrations.AddField(
            model_name='activationofdeactivatedmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300),
        ),
        migrations.AddField(
            model_name='deactivationofmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300),
        ),
        migrations.AddField(
            model_name='updateonproductsmanufactured',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber'),
        ),
        migrations.AddField(
            model_name='updateonproductsmanufactured',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300),
        ),
    ]
