# Generated by Django 3.2.13 on 2023-03-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230313_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReissuanceOfCertForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200)),
                ('cac_reg_number', models.CharField(max_length=200)),
                ('tax_identification_number', models.CharField(max_length=200)),
                ('man_reg_number', models.CharField(max_length=200)),
                ('company_official_email', models.CharField(max_length=200)),
                ('company_official_website', models.CharField(max_length=200)),
                ('corporate_addresse', models.CharField(max_length=200)),
                ('other_factory_location', models.JSONField(default=dict)),
                ('products_manufactured', models.JSONField(default=dict)),
                ('list_of_imported_materials_used_in_production', models.JSONField(default=dict)),
                ('list_of_local_materials_used_in_production', models.JSONField(default=dict)),
                ('managing_director_email', models.EmailField(max_length=254)),
                ('managing_director_phone', models.CharField(max_length=200)),
                ('chief_finance_officer_phone', models.CharField(max_length=200)),
                ('chief_finance_officer_email', models.CharField(max_length=200)),
                ('head_of_admin_phone', models.CharField(max_length=200)),
                ('head_of_admin_email', models.CharField(max_length=200)),
                ('head_of_corporate_affair_phone', models.CharField(max_length=200)),
                ('head_of_corporate_affair_email', models.CharField(max_length=200)),
                ('officer_handling_man_issues_in_your_company_phone', models.CharField(max_length=200)),
                ('officer_handling_man_issues_in_your_company_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyTurnOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('attachment', models.FileField(upload_to='attachment_finicial_statement/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ReissuanceOfCertServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reissuance_of_cert_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.reissuanceofcertform')),
            ],
        ),
        migrations.AddField(
            model_name='reissuanceofcertform',
            name='year_turn_over',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.yearlyturnover'),
        ),
        migrations.AddField(
            model_name='changeofname',
            name='reissuance_of_cert_form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.reissuanceofcertform'),
        ),
        migrations.AddField(
            model_name='lossofcertificateservices',
            name='reissuance_of_cert_form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.reissuanceofcertform'),
        ),
    ]
