# Generated by Django 3.2.13 on 2023-03-14 12:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230314_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyturnover',
            name='attachment',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='attachment_finicial_statement/%d/'),
        ),
    ]
