# Generated by Django 3.2.13 on 2023-07-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rel8Tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flutterwave_publickey',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='client',
            name='flutterwave_secret',
            field=models.TextField(default='null'),
        ),
    ]
