# Generated by Django 3.2.13 on 2022-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rel8Tenant', '0002_periodictasktenantlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paystack_publickey',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='client',
            name='paystack_secret',
            field=models.TextField(default='null'),
        ),
    ]
