# Generated by Django 3.2.13 on 2023-03-09 06:47

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_docs',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='meeting_docs/%d/'),
        ),
        migrations.CreateModel(
            name='EventProxyAttendies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.JSONField(default={'participants': []})),
                ('event_due_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdue_user')),
            ],
        ),
    ]
