# Generated by Django 3.2.13 on 2023-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20230309_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproxyattendies',
            name='participants',
            field=models.JSONField(default=dict),
        ),
    ]
