# Generated by Django 3.2.13 on 2023-02-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_membershipgrade_member'),
        ('event', '0002_auto_20230217_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='chapters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters'),
        ),
        migrations.AlterField(
            model_name='event',
            name='commitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commiteegroup'),
        ),
    ]
