# Generated by Django 3.2.13 on 2023-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20230220_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organiserImage',
            field=models.ImageField(default=None, null=True, upload_to='event_organiser/%d/'),
        ),
    ]
