# Generated by Django 3.2.13 on 2022-12-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_photo'),
        ('event', '0003_rescheduleeventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exco',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.excorole'),
        ),
    ]
