# Generated by Django 3.2.13 on 2023-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
