# Generated by Django 4.2.15 on 2024-08-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_event_is_special"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="public",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no"), ("both", "both")],
                default="no",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="PublicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
            ],
        ),
    ]
