# Generated by Django 4.2.15 on 2024-08-28 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_event_public_alter_event_address_publicevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicevent",
            name="paystack_key",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="publicevent",
            name="registered_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventdue_user",
            name="paystack_key",
            field=models.TextField(default="", unique=True),
        ),
    ]
