# Generated by Django 4.2.15 on 2024-08-28 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_remove_publicevent_paystack_key_publiceventpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicevent",
            name="registered_at",
        ),
        migrations.AddField(
            model_name="publiceventpayment",
            name="paid_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
