# Generated by Django 4.2.15 on 2024-08-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_remove_publicevent_registered_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublicEventPayment",
        ),
    ]
