# Generated by Django 3.2.13 on 2025-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_publicevent'),
        ('event', '0012_delete_publiceventpayment'),
    ]

    operations = [
    ]
