# Generated by Django 3.2.13 on 2023-03-22 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManProspectiveMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=600)),
                ('telephone_number', models.CharField(max_length=600)),
                ('cac_registration_number', models.TextField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('corporate_office_addresse', models.TextField()),
                ('has_paid', models.BooleanField(default=False)),
                ('paystack', models.CharField(max_length=300)),
                ('application_status', models.CharField(choices=[('approval_in_progress', 'Approval In Progress'), ('approval_in_principle_granted', 'Approval In Principle Granted'), ('final_approval', 'Final Approval')], default='approval_in_progress', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManProspectiveMemberFormTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_affairs_commision', models.FileField(upload_to='corporate_affairs_commision/')),
                ('letter_of_breakdown_of_payment_and_docs_attached', models.FileField(upload_to='letter_of_breakdown_of_payment_and_docs_attached/')),
                ('first_year_of_buisness_plan', models.FileField(upload_to='first_year_of_buisness_plan/')),
                ('second_year_of_buisness_plan', models.FileField(upload_to='second_year_of_buisness_plan/')),
                ('photocopy_of_your_reciept_issued_on_purchase_of_applicant_form', models.FileField(upload_to='photocopy_of_your_reciept_issued_on_purchase_of_applicant_form/')),
                ('prospective_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.manprospectivememberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ManProspectiveMemberFormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cac_registration_number', models.TextField(max_length=600)),
                ('name_of_company', models.CharField(max_length=600)),
                ('tax_identification_number', models.TextField()),
                ('corporate_office_addresse', models.TextField()),
                ('office_bus_stop', models.TextField()),
                ('office_city', models.TextField()),
                ('office_lga', models.TextField()),
                ('office_state', models.CharField(max_length=300)),
                ('postal_addresse', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=13)),
                ('email_addresse', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('factoru_details', models.TextField()),
                ('legal_status_of_company', models.CharField(max_length=100)),
                ('number_of_female_expatriates', models.IntegerField()),
                ('number_of_male_expatriates', models.IntegerField()),
                ('local_share_capital', models.TextField()),
                ('foreign_share_capital', models.TextField()),
                ('ownership_structure_equity_local', models.TextField()),
                ('ownership_structure_equity_foregin', models.TextField()),
                ('total_value_of_land_asset', models.TextField()),
                ('total_value_of_building_asset', models.TextField()),
                ('total_value_of_other_asset', models.TextField()),
                ('installed_capacity', models.TextField()),
                ('current_sales_turnover', models.TextField()),
                ('projected_sales_turnover', models.TextField()),
                ('are_your_product_exported', models.TextField()),
                ('company_contact_infomation', models.TextField()),
                ('designation', models.TextField()),
                ('name_of_md_or_ceo_of_company', models.TextField()),
                ('selectdate_of_registration', models.DateField()),
                ('upload_signature', models.ImageField(upload_to='upload_signature/%m/')),
                ('prospective_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.manprospectivememberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AllRawMaterialsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_raw_materials', models.TextField()),
                ('percent_of_local_raw_materials', models.IntegerField()),
                ('man_prospective_member_form_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.manprospectivememberformone')),
            ],
        ),
        migrations.CreateModel(
            name='AllProductManufactured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_manufactured', models.TextField()),
                ('certificates', models.TextField()),
                ('man_prospective_member_form_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.manprospectivememberformone')),
            ],
        ),
    ]
