# Generated by Django 3.2.13 on 2023-03-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0002_registrationamountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
