# Generated by Django 3.2.13 on 2023-03-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0003_manprospectivememberprofile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='are_your_product_exported',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='company_contact_infomation',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='current_sales_turnover',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='designation',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='foreign_share_capital',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='installed_capacity',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='local_share_capital',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='name_of_md_or_ceo_of_company',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='number_of_female_expatriates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='number_of_male_expatriates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='ownership_structure_equity_foregin',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='ownership_structure_equity_local',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='projected_sales_turnover',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='selectdate_of_registration',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='total_value_of_building_asset',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='total_value_of_land_asset',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='total_value_of_other_asset',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformone',
            name='upload_signature',
            field=models.ImageField(default=None, null=True, upload_to='upload_signature/%m/'),
        ),
    ]
