# Generated by Django 3.2.13 on 2023-03-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0004_auto_20230323_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrawmaterialsused',
            name='man_prospective_member_form_one',
        ),
        migrations.DeleteModel(
            name='AllProductManufactured',
        ),
        migrations.DeleteModel(
            name='AllRawMaterialsUsed',
        ),
    ]
