# Generated by Django 3.2.13 on 2023-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0006_auto_20230323_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberformone',
            name='number_of_female_permanent_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manprospectivememberformone',
            name='number_of_male_permanent_staff',
            field=models.IntegerField(default=0),
        ),
    ]
