# Generated by Django 3.2.13 on 2023-04-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospectivemember', '0007_auto_20230327_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetPropectiveMembershipRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propective_members_text_fields', models.JSONField(default=dict)),
                ('propective_members_file_fields', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectiveMemberFormTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectiveMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=600)),
                ('telephone_number', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.TextField()),
                ('has_paid', models.BooleanField(default=False)),
                ('paystack', models.CharField(max_length=300)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('application_status', models.CharField(choices=[('approval_in_progress', 'Approval In Progress'), ('approval_in_principle_granted', 'Approval In Principle Granted'), ('final_approval', 'Final Approval')], default='approval_in_progress', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectiveMemberFormTwoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='prospectivemember_file/%m/')),
                ('form_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.prospectivememberformtwo')),
            ],
        ),
        migrations.AddField(
            model_name='prospectivememberformtwo',
            name='prospective_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.prospectivememberprofile'),
        ),
        migrations.CreateModel(
            name='ProspectiveMemberFormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(default=dict)),
                ('prospective_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.prospectivememberprofile')),
            ],
        ),
    ]
