# Generated by Django 3.2.13 on 2023-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0008_auto_20230407_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectivememberprofile',
            name='paystack_key',
            field=models.CharField(default='.', max_length=300),
        ),
    ]
