# Generated by Django 3.2.13 on 2023-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0009_prospectivememberprofile_paystack_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsetpropectivemembershiprule',
            name='propective_members_file_fields',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adminsetpropectivemembershiprule',
            name='propective_members_text_fields',
            field=models.JSONField(default=None, null=True),
        ),
    ]
