# Generated by Django 3.2.13 on 2023-04-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0010_auto_20230411_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsetpropectivemembershiprule',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
