# Generated by Django 3.2.13 on 2023-01-06 11:06

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_exco', models.BooleanField(default=False)),
                ('is_committe', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(null=True)),
                ('dislikes', models.IntegerField(null=True)),
                ('body', models.TextField(default=' ')),
                ('image', models.ImageField(default=None, null=True, upload_to='newsImage/%d/')),
                ('danload', models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='newsFileDanload/%d/')),
                ('chapters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters')),
                ('commitee_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commiteegroup')),
                ('exco', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.excorole')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragragh', models.TextField(blank=True, default=' ', null=True)),
                ('heading', models.TextField(blank=True, default=' ', null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
            ],
        ),
    ]
