# Generated by Django 3.2.13 on 2022-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publicationparagraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='danload',
            field=models.FileField(default=None, null=True, upload_to='newsFileDanload/%/'),
        ),
    ]
