# Generated by Django 3.2.13 on 2022-09-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publication_danload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationparagraph',
            name='heading',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='publicationparagraph',
            name='paragragh',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
