# Generated by Django 3.2.13 on 2022-09-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usermemberinfo_value'),
        ('publication', '0004_auto_20220913_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='commitee_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commiteegroup'),
        ),
    ]
