# Generated by Django 3.2.13 on 2022-09-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usermemberinfo_value'),
        ('publication', '0005_alter_publication_commitee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='chapters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='danload',
            field=models.FileField(default=None, null=True, upload_to='newsFileDanload/%d/'),
        ),
    ]
