# Generated by Django 3.2.13 on 2022-10-04 06:10

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20220913_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='danload',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='newsFileDanload/%d/'),
        ),
    ]
