# Generated by Django 3.2.13 on 2022-12-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_alter_excorole_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReshedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reschedule_date', models.DateTimeField(default=None, null=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.memeber')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.memeber')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('details', models.TextField(default='..')),
                ('date_for', models.DateTimeField(default=None, null=True)),
                ('chapters', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters')),
                ('exco', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.excorole')),
            ],
        ),
    ]
