# Generated by Django 3.2.13 on 2022-12-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendies',
            name='meeting',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetingreshedule',
            name='meeting',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting'),
        ),
    ]
