# Generated by Django 3.2.13 on 2023-02-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='addresse',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='event_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
