# Generated by Django 3.2.13 on 2022-12-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_excorole_member'),
        ('meeting', '0002_auto_20221214_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='chapters',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chapters'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='exco',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.excorole'),
        ),
    ]
