# Generated by Django 3.2.13 on 2023-02-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_memberemploymenthistory_member'),
        ('meeting', '0002_meetingapology'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='membership_grade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.membershipgrade'),
        ),
    ]
