# Generated by Django 3.2.13 on 2023-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meetingproxyattendies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingproxyattendies',
            name='participants',
            field=models.JSONField(default=dict),
        ),
    ]
