# Generated by Django 3.2.13 on 2023-02-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_memberemploymenthistory_member'),
        ('meeting', '0003_meeting_membership_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='commitee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commiteegroup'),
        ),
    ]
