# Generated by Django 3.2.13 on 2023-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_meetingproxyattendies_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='meeting_image/%d/'),
        ),
    ]
