# Generated by Django 3.2.13 on 2023-02-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_meeting_commitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='organiserImage',
            field=models.ImageField(default=None, null=True, upload_to='meeting_organiser/%d/'),
        ),
    ]
