# Generated by Django 3.2.13 on 2023-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dueapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='due',
            name='is_deactivate_users',
            field=models.BooleanField(default=True),
        ),
    ]
