# Generated by Django 3.2.13 on 2023-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dueapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='alumni_year',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
