# Generated by Django 3.2.13 on 2023-02-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dueapp', '0003_auto_20230206_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='is_on_create',
            field=models.BooleanField(default=False),
        ),
    ]
