# Generated by Django 3.2.13 on 2023-04-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_user_type'),
        ('Dueapp', '0003_alter_due_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='exco',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.excorole'),
        ),
    ]
