# Generated by Django 3.2.13 on 2023-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dueapp', '0004_due_exco'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='item_code',
            field=models.TextField(default=''),
        ),
    ]
