# Generated by Django 4.2.15 on 2024-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dueapp", "0007_due_user_item_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deactivatingdue_user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
